### ISSUE TITLE
Plugin not enabling

### ISSUE THREAD

**Issue by Clevvas** [SilPho/medal-collection#7]
reporting script compilation failed 
log showing: 
'Medalcollection.op/:/MoreMedals.as(52, 80): ERR: No Matching symbol 'Medalsfound'
Error occuring since updating to 2.4

**Comment by Clevvas** [comment]
installed Warriormedals to test - works with warrior medals installed

**Comment by SilPho** [comment]
Shoot. Thanks for the message. I'll get that fixed up as soon as possible

**Comment by SilPho** [comment]
This has now been fixed in version 2.4.1, which is available now.
